2024-06-20 15:41:00,810 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-06-20 15:41:00,812 INFO supervisord started with pid 1
2024-06-20 15:41:01,816 INFO spawned: 'django' with pid 9
2024-06-20 15:41:02,260 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140613316750704 for <Subprocess at 140613316752864 with name django in state STARTING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|220] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|270] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|204] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|173] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])
2024-06-20 15:41:03,262 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-20 16:07:12,798 WARN received SIGTERM indicating exit request
2024-06-20 16:07:12,798 INFO waiting for django to die
2024-06-20 16:07:12,856 INFO stopped: django (exit status 0)
2024-06-20 16:07:16,960 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-06-20 16:07:16,962 INFO supervisord started with pid 1
2024-06-20 16:07:17,964 INFO spawned: 'django' with pid 9
2024-06-20 16:07:18,468 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140312866008384 for <Subprocess at 140312866010544 with name django in state STARTING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|220] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|270] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|204] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|173] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])
2024-06-20 16:07:19,469 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-20 16:09:54,618 WARN received SIGTERM indicating exit request
2024-06-20 16:09:54,619 INFO waiting for django to die
2024-06-20 16:09:54,688 INFO stopped: django (exit status 0)
2024-06-20 16:09:56,144 CRIT Supervisor is running as root.  Privileges were not dropped because no user is specified in the config file.  If you intend to run as root, you can set user=root in the config file to avoid this message.
2024-06-20 16:09:56,145 INFO supervisord started with pid 1
2024-06-20 16:09:57,148 INFO spawned: 'django' with pid 9
2024-06-20 16:09:57,620 CRIT uncaptured python exception, closing channel <POutputDispatcher at 140572110155072 for <Subprocess at 140572110157232 with name django in state STARTING> (stderr)> (<class 'OSError'>:[Errno 29] Illegal seek [/usr/lib/python3/dist-packages/supervisor/supervisord.py|runforever|220] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|handle_read_event|270] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|record_output|204] [/usr/lib/python3/dist-packages/supervisor/dispatchers.py|_log|173] [/usr/lib/python3/dist-packages/supervisor/loggers.py|info|327] [/usr/lib/python3/dist-packages/supervisor/loggers.py|log|345] [/usr/lib/python3/dist-packages/supervisor/loggers.py|emit|227] [/usr/lib/python3/dist-packages/supervisor/loggers.py|doRollover|264])
2024-06-20 16:09:58,621 INFO success: django entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
2024-06-20 16:10:04,627 WARN received SIGTERM indicating exit request
2024-06-20 16:10:04,627 INFO waiting for django to die
2024-06-20 16:10:04,680 INFO stopped: django (exit status 0)
